// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace SQSTest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// AssertionSoekResultatFisk - Use 'AssertionSoekResultatFiskExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertionSoekResultatFisk()
        {
            #region Variable Declarations
            HtmlDiv uIFiskeoppskrifterSunnPane = this.UIFiskKvasirInternetExWindow.UIFiskKvasirDocument.UINamemaster1slave11coFrame.UIHttpwwwgooglecomafsaDocument.UIE19Pane.UIFiskeoppskrifterSunnPane;
            #endregion

            // Verify that the 'FriendlyName' property of 'Fiskeoppskrifter - Sunne og gode oppskri' pane contains 'Fiskeoppskrifter - Sunne og gode oppskri'
            StringAssert.Contains(uIFiskeoppskrifterSunnPane.FriendlyName, this.AssertionSoekResultatFiskExpectedValues.UIFiskeoppskrifterSunnPaneFriendlyName, "FirstElementContains");
        }
        
        /// <summary>
        /// CloseIE
        /// </summary>
        public void CloseIE()
        {
            #region Variable Declarations
            BrowserWindow uIFiskKvasirInternetExWindow1 = this.UIFiskKvasirInternetExWindow1;
            #endregion

            // Perform Close on Browser Window
            uIFiskKvasirInternetExWindow1.Close();
        }
        
        /// <summary>
        /// GoToKvasir - Use 'GoToKvasirParams' to pass parameters into this method.
        /// </summary>
        public void GoToKvasir()
        {
            #region Variable Declarations
            BrowserWindow uIMSNNorgeOutlookcomHoWindow = this.UIMSNNorgeOutlookcomHoWindow;
            #endregion

            // Go to web page 'http://kvasir.no/'
            uIMSNNorgeOutlookcomHoWindow.NavigateToUrl(new System.Uri(this.GoToKvasirParams.UIMSNNorgeOutlookcomHoWindowUrl));
        }
        
        /// <summary>
        /// SoekForFisk - Use 'SoekForFiskParams' to pass parameters into this method.
        /// </summary>
        public void SoekForFisk()
        {
            #region Variable Declarations
            HtmlEdit uISøketternoeEdit = this.UIKvasirEnsmarteremåteWindow.UIKvasirEnsmarteremåteDocument.UISøketternoeEdit;
            #endregion

            // Type 'fisk' in 'Søk etter noe...' text box
            uISøketternoeEdit.Text = this.SoekForFiskParams.UISøketternoeEditText;

            // Type '{Enter}' in 'Søk etter noe...' text box
            Keyboard.SendKeys(uISøketternoeEdit, this.SoekForFiskParams.UISøketternoeEditSendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// StartIE - Use 'StartIEParams' to pass parameters into this method.
        /// </summary>
        public void StartIE()
        {

            // Go to web page 'http://go.microsoft.com/fwlink/p/?LinkId=255141' using new browser instance
            BrowserWindow gomicrosoftcomBrowser = BrowserWindow.Launch(new System.Uri(this.StartIEParams.Url));
        }
        
        #region Properties
        public virtual AssertionSoekResultatFiskExpectedValues AssertionSoekResultatFiskExpectedValues
        {
            get
            {
                if ((this.mAssertionSoekResultatFiskExpectedValues == null))
                {
                    this.mAssertionSoekResultatFiskExpectedValues = new AssertionSoekResultatFiskExpectedValues();
                }
                return this.mAssertionSoekResultatFiskExpectedValues;
            }
        }
        
        public virtual GoToKvasirParams GoToKvasirParams
        {
            get
            {
                if ((this.mGoToKvasirParams == null))
                {
                    this.mGoToKvasirParams = new GoToKvasirParams();
                }
                return this.mGoToKvasirParams;
            }
        }
        
        public virtual SoekForFiskParams SoekForFiskParams
        {
            get
            {
                if ((this.mSoekForFiskParams == null))
                {
                    this.mSoekForFiskParams = new SoekForFiskParams();
                }
                return this.mSoekForFiskParams;
            }
        }
        
        public virtual StartIEParams StartIEParams
        {
            get
            {
                if ((this.mStartIEParams == null))
                {
                    this.mStartIEParams = new StartIEParams();
                }
                return this.mStartIEParams;
            }
        }
        
        public UIFyrstekakeGooglesøkIWindow UIFyrstekakeGooglesøkIWindow
        {
            get
            {
                if ((this.mUIFyrstekakeGooglesøkIWindow == null))
                {
                    this.mUIFyrstekakeGooglesøkIWindow = new UIFyrstekakeGooglesøkIWindow();
                }
                return this.mUIFyrstekakeGooglesøkIWindow;
            }
        }
        
        public UIMSNNorgeOutlookcomHoWindow UIMSNNorgeOutlookcomHoWindow
        {
            get
            {
                if ((this.mUIMSNNorgeOutlookcomHoWindow == null))
                {
                    this.mUIMSNNorgeOutlookcomHoWindow = new UIMSNNorgeOutlookcomHoWindow();
                }
                return this.mUIMSNNorgeOutlookcomHoWindow;
            }
        }
        
        public UIKvasirEnsmarteremåteWindow UIKvasirEnsmarteremåteWindow
        {
            get
            {
                if ((this.mUIKvasirEnsmarteremåteWindow == null))
                {
                    this.mUIKvasirEnsmarteremåteWindow = new UIKvasirEnsmarteremåteWindow();
                }
                return this.mUIKvasirEnsmarteremåteWindow;
            }
        }
        
        public UIFiskKvasirInternetExWindow UIFiskKvasirInternetExWindow
        {
            get
            {
                if ((this.mUIFiskKvasirInternetExWindow == null))
                {
                    this.mUIFiskKvasirInternetExWindow = new UIFiskKvasirInternetExWindow();
                }
                return this.mUIFiskKvasirInternetExWindow;
            }
        }
        
        public UIFiskKvasirInternetExWindow1 UIFiskKvasirInternetExWindow1
        {
            get
            {
                if ((this.mUIFiskKvasirInternetExWindow1 == null))
                {
                    this.mUIFiskKvasirInternetExWindow1 = new UIFiskKvasirInternetExWindow1();
                }
                return this.mUIFiskKvasirInternetExWindow1;
            }
        }
        #endregion
        
        #region Fields
        private AssertionSoekResultatFiskExpectedValues mAssertionSoekResultatFiskExpectedValues;
        
        private GoToKvasirParams mGoToKvasirParams;
        
        private SoekForFiskParams mSoekForFiskParams;
        
        private StartIEParams mStartIEParams;
        
        private UIFyrstekakeGooglesøkIWindow mUIFyrstekakeGooglesøkIWindow;
        
        private UIMSNNorgeOutlookcomHoWindow mUIMSNNorgeOutlookcomHoWindow;
        
        private UIKvasirEnsmarteremåteWindow mUIKvasirEnsmarteremåteWindow;
        
        private UIFiskKvasirInternetExWindow mUIFiskKvasirInternetExWindow;
        
        private UIFiskKvasirInternetExWindow1 mUIFiskKvasirInternetExWindow1;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertionSoekResultatFisk'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class AssertionSoekResultatFiskExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'FriendlyName' property of 'Fiskeoppskrifter - Sunne og gode oppskri' pane contains 'Fiskeoppskrifter - Sunne og gode oppskri'
        /// </summary>
        public string UIFiskeoppskrifterSunnPaneFriendlyName = "Fiskeoppskrifter - Sunne og gode oppskri";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'GoToKvasir'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class GoToKvasirParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://kvasir.no/'
        /// </summary>
        public string UIMSNNorgeOutlookcomHoWindowUrl = "http://kvasir.no/";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SoekForFisk'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class SoekForFiskParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'fisk' in 'Søk etter noe...' text box
        /// </summary>
        public string UISøketternoeEditText = "fisk";
        
        /// <summary>
        /// Type '{Enter}' in 'Søk etter noe...' text box
        /// </summary>
        public string UISøketternoeEditSendKeys = "{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'StartIE'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class StartIEParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://go.microsoft.com/fwlink/p/?LinkId=255141' using new browser instance
        /// </summary>
        public string Url = "http://go.microsoft.com/fwlink/p/?LinkId=255141";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIFyrstekakeGooglesøkIWindow : BrowserWindow
    {
        
        public UIFyrstekakeGooglesøkIWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "fyrstekake - Google-søk";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("fyrstekake - Google-søk");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIFyrstekakeGooglesøkDocument UIFyrstekakeGooglesøkDocument
        {
            get
            {
                if ((this.mUIFyrstekakeGooglesøkDocument == null))
                {
                    this.mUIFyrstekakeGooglesøkDocument = new UIFyrstekakeGooglesøkDocument(this);
                }
                return this.mUIFyrstekakeGooglesøkDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIFyrstekakeGooglesøkDocument mUIFyrstekakeGooglesøkDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIFyrstekakeGooglesøkDocument : HtmlDocument
    {
        
        public UIFyrstekakeGooglesøkDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "gsr";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "fyrstekake - Google-søk";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://www.google.no/?gfe_rd=cr&ei=_HjYVOahBMiq8weZroG4Cg&gws_rd=ssl#q=fyrstekak" +
                "e";
            this.WindowTitles.Add("fyrstekake - Google-søk");
            #endregion
        }
        
        #region Properties
        public UIRsoCustom UIRsoCustom
        {
            get
            {
                if ((this.mUIRsoCustom == null))
                {
                    this.mUIRsoCustom = new UIRsoCustom(this);
                }
                return this.mUIRsoCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIRsoCustom mUIRsoCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIRsoCustom : HtmlCustom
    {
        
        public UIRsoCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "OL";
            this.SearchProperties["Id"] = "rso";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"rso\" eid=\"_3jYVIT6MYKC7gbGxYDIDw\"";
            this.FilterProperties["TagInstance"] = "2";
            this.WindowTitles.Add("fyrstekake - Google-søk");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UIFyrstekakeerensaftigPane
        {
            get
            {
                if ((this.mUIFyrstekakeerensaftigPane == null))
                {
                    this.mUIFyrstekakeerensaftigPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIFyrstekakeerensaftigPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIFyrstekakeerensaftigPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIFyrstekakeerensaftigPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Fyrstekake er en saftig og god formkake ";
                    this.mUIFyrstekakeerensaftigPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIFyrstekakeerensaftigPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "st";
                    this.mUIFyrstekakeerensaftigPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"st\"";
                    this.mUIFyrstekakeerensaftigPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "54";
                    this.mUIFyrstekakeerensaftigPane.WindowTitles.Add("fyrstekake - Google-søk");
                    #endregion
                }
                return this.mUIFyrstekakeerensaftigPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUIFyrstekakeerensaftigPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIMSNNorgeOutlookcomHoWindow : BrowserWindow
    {
        
        public UIMSNNorgeOutlookcomHoWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "MSN Norge - Outlook.com, Hotmail, Skype, Bing og siste nyheter";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("MSN Norge - Outlook.com, Hotmail, Skype, Bing og siste nyheter");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIKvasirEnsmarteremåteWindow : BrowserWindow
    {
        
        public UIKvasirEnsmarteremåteWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Kvasir - En smartere måte å lete på";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Kvasir - En smartere måte å lete på");
            this.WindowTitles.Add("fisk - Kvasir");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIKvasirEnsmarteremåteDocument UIKvasirEnsmarteremåteDocument
        {
            get
            {
                if ((this.mUIKvasirEnsmarteremåteDocument == null))
                {
                    this.mUIKvasirEnsmarteremåteDocument = new UIKvasirEnsmarteremåteDocument(this);
                }
                return this.mUIKvasirEnsmarteremåteDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIKvasirEnsmarteremåteDocument mUIKvasirEnsmarteremåteDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIKvasirEnsmarteremåteDocument : HtmlDocument
    {
        
        public UIKvasirEnsmarteremåteDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Kvasir - En smartere måte å lete på";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://kvasir.no/";
            this.WindowTitles.Add("Kvasir - En smartere måte å lete på");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UISøketternoeEdit
        {
            get
            {
                if ((this.mUISøketternoeEdit == null))
                {
                    this.mUISøketternoeEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUISøketternoeEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "q";
                    this.mUISøketternoeEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "q";
                    this.mUISøketternoeEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUISøketternoeEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUISøketternoeEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "Søk etter noe...";
                    this.mUISøketternoeEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "search-input tabnavigate";
                    this.mUISøketternoeEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"q\" title=\"Søk etter noe...\" class=";
                    this.mUISøketternoeEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUISøketternoeEdit.WindowTitles.Add("Kvasir - En smartere måte å lete på");
                    #endregion
                }
                return this.mUISøketternoeEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUISøketternoeEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIFiskKvasirInternetExWindow : BrowserWindow
    {
        
        public UIFiskKvasirInternetExWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "fisk - Kvasir";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("fisk - Kvasir");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIFiskKvasirDocument UIFiskKvasirDocument
        {
            get
            {
                if ((this.mUIFiskKvasirDocument == null))
                {
                    this.mUIFiskKvasirDocument = new UIFiskKvasirDocument(this);
                }
                return this.mUIFiskKvasirDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIFiskKvasirDocument mUIFiskKvasirDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIFiskKvasirDocument : HtmlDocument
    {
        
        public UIFiskKvasirDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "fisk - Kvasir";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/alle";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://kvasir.no/alle?q=fisk";
            this.WindowTitles.Add("fisk - Kvasir");
            #endregion
        }
        
        #region Properties
        public UINamemaster1slave11coFrame UINamemaster1slave11coFrame
        {
            get
            {
                if ((this.mUINamemaster1slave11coFrame == null))
                {
                    this.mUINamemaster1slave11coFrame = new UINamemaster1slave11coFrame(this);
                }
                return this.mUINamemaster1slave11coFrame;
            }
        }
        #endregion
        
        #region Fields
        private UINamemaster1slave11coFrame mUINamemaster1slave11coFrame;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UINamemaster1slave11coFrame : HtmlIFrame
    {
        
        public UINamemaster1slave11coFrame(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "master-1";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = @"{""name"":""master-1"",""slave-1-1"":{""container"":""adcontainer2"",""linkTarget"":""_blank"",""lines"":3,""colorTitleLink"":""#18428F"",""colorDomainLink"":""#388222"",""colorBorder"":""#E8E7D8"",""fontSizeTitle"":""16px"",""fontSizeDescription"":""13px"",""fontSizeDomainLink"":""13px"",""noTitleUnderline"":true,""borderSelections"":""top"",""adIconLocation"":""ad-left"",""domainLinkAboveDescription"":""true"",""plaFormat"":""twoColumn"",""detailedAttribution"":true,""type"":""ads"",""columns"":1,""horizontalAlignment"":""left"",""resultsPageQueryParam"":""query""},""master-1"":{""container"":""adcontainer1"",""linkTarget"":""_blank"",""lines"":3,""colorTitleLink"":""#18428F"",""colorDomainLink"":""#388222"",""colorBorder"":""#E8E7D8"",""fontSizeTitle"":""16px"",""fontSizeDescription"":""13px"",""fontSizeDomainLink"":""13px"",""noTitleUnderline"":true,""borderSelections"":""bottom"",""adIconLocation"":""ad-left"",""domainLinkAboveDescription"":""true"",""plaFormat"":""twoColumn"",""detailedAttribution"":true,""type"":""ads"",""columns"":1,""horizontalAlignment"":""left"",""resultsPageQueryParam"":""query""}}";
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = @"/afs/ads%3Fq=fisk&lo=true&adpage=1&adrep=2&po=true&r=m&fexp=2631602%252C21404%252C7000108&client=kvasir&channel=test_ads_num_4-4-seller-ratings-plus-ones-domain-link-above-description&hl=no&adsafe=medium&type=0&oe=UTF-8&ie=UTF-8&jsei=4&format=p4%257Cn4&ad=n4p4&nocache=8941423554056747&num=0&output=uds_ads_only&v=3&adlh=on&adext=as1%252Cl1%252Csr1&bsl=10&u_his=3&u_tz=60&dt=1423554056748&u_w=1920&u_h=1200&biw=1032&bih=797&psw=1032&psh=1491&frm=0&uio=uv3cs1po1sr1va1sl1lo1-lHst16sd13sv13da1-lhst16sd13sv13da1&rurl=http%253A%252F%252Fkvasir.no%252Falle%253Fq%253Dfisk&referer=http%253A%252F%252Fkvasir.no%252F%23master-1";
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = @"//www.google.com/afs/ads?q=fisk&lo=true&adpage=1&adrep=2&po=true&r=m&fexp=2631602%2C21404%2C7000108&client=kvasir&channel=test_ads_num_4-4-seller-ratings-plus-ones-domain-link-above-description&hl=no&adsafe=medium&type=0&oe=UTF-8&ie=UTF-8&jsei=4&format=p4%7Cn4&ad=n4p4&nocache=8941423554056747&num=0&output=uds_ads_only&v=3&adlh=on&adext=as1%2Cl1%2Csr1&bsl=10&u_his=3&u_tz=60&dt=1423554056748&u_w=1920&u_h=1200&biw=1032&bih=797&psw=1032&psh=1491&frm=0&uio=uv3cs1po1sr1va1sl1lo1-lHst16sd13sv13da1-lhst16sd13sv13da1&rurl=http%3A%2F%2Fkvasir.no%2Falle%3Fq%3Dfisk&referer=http%3A%2F%2Fkvasir.no%2F#master-1";
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "name=\'{\"name\":\"master-1\",\"slave-1-1\":{\"c";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("fisk - Kvasir");
            #endregion
        }
        
        #region Properties
        public UIHttpwwwgooglecomafsaDocument UIHttpwwwgooglecomafsaDocument
        {
            get
            {
                if ((this.mUIHttpwwwgooglecomafsaDocument == null))
                {
                    this.mUIHttpwwwgooglecomafsaDocument = new UIHttpwwwgooglecomafsaDocument(this);
                }
                return this.mUIHttpwwwgooglecomafsaDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHttpwwwgooglecomafsaDocument mUIHttpwwwgooglecomafsaDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHttpwwwgooglecomafsaDocument : HtmlDocument
    {
        
        public UIHttpwwwgooglecomafsaDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/afs/ads";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = @"http://www.google.com/afs/ads?q=fisk&lo=true&adpage=1&adrep=2&po=true&r=m&fexp=2631602%2C21404%2C7000108&client=kvasir&channel=test_ads_num_4-4-seller-ratings-plus-ones-domain-link-above-description&hl=no&adsafe=medium&type=0&oe=UTF-8&ie=UTF-8&jsei=4&format=p4%7Cn4&ad=n4p4&nocache=8941423554056747&num=0&output=uds_ads_only&v=3&adlh=on&adext=as1%2Cl1%2Csr1&bsl=10&u_his=3&u_tz=60&dt=1423554056748&u_w=1920&u_h=1200&biw=1032&bih=797&psw=1032&psh=1491&frm=0&uio=uv3cs1po1sr1va1sl1lo1-lHst16sd13sv13da1-lhst16sd13sv13da1&rurl=http%3A%2F%2Fkvasir.no%2Falle%3Fq%3Dfisk&referer=http%3A%2F%2Fkvasir.no%2F#master-1";
            this.WindowTitles.Add("fisk - Kvasir");
            #endregion
        }
        
        #region Properties
        public UIE19Pane UIE19Pane
        {
            get
            {
                if ((this.mUIE19Pane == null))
                {
                    this.mUIE19Pane = new UIE19Pane(this);
                }
                return this.mUIE19Pane;
            }
        }
        #endregion
        
        #region Fields
        private UIE19Pane mUIE19Pane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIE19Pane : HtmlDiv
    {
        
        public UIE19Pane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "e19";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Fiskeoppskrifter - Sunne og gode oppskri";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "a_ b_";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"a_ b_\" id=\"e19\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "3";
            this.WindowTitles.Add("fisk - Kvasir");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIFiskeoppskrifterSunnPane
        {
            get
            {
                if ((this.mUIFiskeoppskrifterSunnPane == null))
                {
                    this.mUIFiskeoppskrifterSunnPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIFiskeoppskrifterSunnPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIFiskeoppskrifterSunnPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIFiskeoppskrifterSunnPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Fiskeoppskrifter - Sunne og gode oppskri";
                    this.mUIFiskeoppskrifterSunnPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIFiskeoppskrifterSunnPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "adStd threeLine";
                    this.mUIFiskeoppskrifterSunnPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"adStd threeLine\"";
                    this.mUIFiskeoppskrifterSunnPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "5";
                    this.mUIFiskeoppskrifterSunnPane.WindowTitles.Add("fisk - Kvasir");
                    #endregion
                }
                return this.mUIFiskeoppskrifterSunnPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIFiskeoppskrifterSunnPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIFiskKvasirInternetExWindow1 : BrowserWindow
    {
        
        public UIFiskKvasirInternetExWindow1()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "fisk - Kvasir";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("fisk - Kvasir");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
    }
}
